postgresql:
  image: postgres:9.3
  ports:
    - "5432:5432"
  volumes:
    - .docker/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=sigmah
    - POSTGRES_PASSWORD=sigmah
    - POSTGRES_DB=sigmah
mailhog:
  image: mailhog/mailhog:latest
  ports:
    - "1025:1025"
    - "8025:8025"
tomcat:
  build: ./sigmah-docker/tomcat
  ports:
    - "9999:8080"
  links:
    - postgresql
  volumes:
    - ./target/sigmah-2.2-SNAPSHOT/:/usr/local/tomcat/webapps/sigmah/
